# -*- coding: utf-8 -*-
"""FinBert2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1az-Sbr6s1jmSSrgHzzevVl8rJ381oamv
"""


"""
FINVERSE - AI-Powered Financial Sentiment & Investment Suggestion Pipeline
==========================================================================
Sources  : EODHD · NewsAPI · Yahoo Finance RSS · Alpha Vantage
Model    : ProsusAI/finbert (pretrained, Hugging Face)
Version  : v3 — with full Diagnostic / Debug Mode

HOW TO VERIFY THE PIPELINE IS WORKING:
────────────────────────────────────────────────────────────────────────────
Run with DEBUG_MODE = True  →  see live proof at every stage:
  ✔  Timestamps on every fetched headline (proves live data, not cache)
  ✔  Source tag on each headline (proves which API delivered it)
  ✔  Raw API response sample printed (proves real HTTP call was made)
  ✔  FinBERT self-test on 3 known sentences before processing news
  ✔  Per-headline score + label in the output (proves model is running)
  ✔  Pipeline summary report at the end (counts, sources, timing)

Run with DEBUG_MODE = False →  clean production output only.
────────────────────────────────────────────────────────────────────────────

Dependencies:
    pip install transformers torch requests
"""

import re
import time
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
import requests
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

# ===========================================================================
# CONFIGURATION — edit these before running
# ===========================================================================

EODHD_API_KEY        = "69efb7b9cd4c71.74119032"
NEWSAPI_API_KEY      = "abae4c5f288a4663898d999ce3402312"
ALPHAVANTAGE_API_KEY = "YNP9E9ALWOHDCH79"

MAX_PER_SOURCE = 8     # Headlines fetched per API (before filtering)
MAX_HEADLINES  = 30    # Hard cap passed to FinBERT
FINBERT_MODEL  = "ProsusAI/finbert"

# ── Set this to True to see full verification output ──────────────────────
DEBUG_MODE = False


# ===========================================================================
# DEBUG HELPERS
# ===========================================================================

def dprint(*args, **kwargs):
    """Print only when DEBUG_MODE is on."""
    if DEBUG_MODE:
        print(*args, **kwargs)


def utc_now() -> str:
    """Return current UTC time as a readable string — proves data is live."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


# ===========================================================================
# FINANCE RELEVANCE FILTER
# ===========================================================================

FINANCE_FILTER_KEYWORDS: list[str] = [
    "stock", "stocks", "equity", "equities", "share", "shares",
    "ipo", "rally", "crash", "bull", "bear", "dividend", "earnings",
    "sensex", "nifty", "bse", "nse", "nasdaq", "dow jones", "s&p", "ftse",
    "mutual fund", "mutual funds", "sip", "nav", "amc", "elss",
    "index fund", "investment", "invest", "investor", "investing",
    "bank", "banking", "interest rate", "repo rate", "central bank",
    "rbi", "fed", "federal reserve", "sebi", "nbfc", "loan", "deposit",
    "inflation", "deflation", "cpi", "wpi",
    "economy", "economic", "gdp", "fiscal", "monetary",
    "recession", "budget", "trade deficit",
    "bond", "yield", "debt", "gold", "crude", "oil",
]

_FINANCE_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(kw) for kw in FINANCE_FILTER_KEYWORDS) + r")\b",
    flags=re.IGNORECASE,
)


def is_finance_relevant(headline: str) -> bool:
    return bool(_FINANCE_PATTERN.search(headline))


def filter_finance_news(headlines: list[str]) -> list[str]:
    return [h for h in headlines if is_finance_relevant(h)]



# ===========================================================================
# FALLBACK DATA
# These provide static headlines if the live APIs fail (e.g. rate limit, 402).
# ===========================================================================

def _fallback_eodhd() -> list[str]:
    return [
        "Major Indian Banks Report Strong Q3 Profits Amid Credit Growth",
        "Sensex Rallies 500 Points as Global Cues Turn Positive",
        "New Fintech Regulations Aim to Boost Digital Payment Security",
        "Manufacturing Sector Output Hits 6-Month High",
        "Foreign Institutional Investors Increase Stake in Indian Tech Firms",
    ]

def _fallback_newsapi() -> list[str]:
    return [
        "Global Markets Await US Fed's Decision on Interest Rates",
        "Oil Prices Steady as Supply Concerns Offset Weak Demand",
        "Tech Giants Announce Multi-Billion Dollar Investment in AI Research",
        "European Stocks Close Higher on Positive Earnings Reports",
        "Emerging Economies Face Inflation Challenges Amid Supply Disruptions",
    ]

def _fallback_yahoo() -> list[str]:
    return [
        "Retail Investors Flock to Mutual Funds as Equity Markets Rise",
        "IPO Market Sees Renewed Interest with Successful Tech Listings",
        "Gold Prices Hit Record Highs on Safe Haven Demand",
        "Real Estate Sector Shows Signs of Recovery in Metropolitan Cities",
        "Auto Sales Surge Ahead of Festive Season in India",
    ]

def _fallback_alphavantage() -> list[str]:
    return [
        "Cryptocurrency Markets Experience High Volatility Following Policy News",
        "Government Announces Infrastructure Projects Worth Billions",
        "Agriculture Sector Benefits from Favorable Monsoon Forecast",
        "Corporate Debt Levels Stabilize as Economic Activity Normalizes",
        "Green Energy Stocks Gain Momentum on Global Sustainability Pushes",
    ]


# ===========================================================================
# STEP 1 — FETCH FROM ALL FOUR SOURCES
# Each fetcher returns: list of dicts → {headline, source, fetched_at}
# The 'source' and 'fetched_at' fields are the live-data proof in debug mode.
# ===========================================================================


def fetch_news_from_eodhd(max_results: int = MAX_PER_SOURCE) -> list[dict]:
    """
    EODHD News API — JSON endpoint.
    Debug proof: prints HTTP status code + first 2 raw titles from response.
    """
    url    = "https://eodhd.com/api/news"
    params = {"api_token": EODHD_API_KEY, "limit": max_results, "fmt": "json"}
    ts     = utc_now()

    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        articles = resp.json()

        # ── DEBUG: prove the HTTP call succeeded and show raw sample ──────
        dprint(f"\n  [DEBUG][EODHD] HTTP {resp.status_code} | fetched at {ts}")
        dprint(f"  [DEBUG][EODHD] Response type   : {type(articles).__name__}"
               f" | Items returned: {len(articles)}")
        if articles:
            dprint(f"  [DEBUG][EODHD] Sample title[0] : {articles[0].get('title','—')}")
        if len(articles) > 1:
            dprint(f"  [DEBUG][EODHD] Sample title[1] : {articles[1].get('title','—')}")

        items = [
            {
                "headline"  : a.get("title", "").strip(),
                "url"       : a.get("link", ""),
                "source"    : "EODHD",
                "fetched_at": ts,
            }
            for a in articles if a.get("title", "").strip()
        ]
        print(f"[EODHD]          Live headlines fetched : {len(items)}")
        return items

    except requests.exceptions.RequestException as e:
        print(f"[EODHD]          FAILED ({e}) — using fallback data.")
        dprint(f"  [DEBUG][EODHD] This means the API key may be invalid or"
               f" network is unavailable. Fallback headlines are NOT live.")
        return [{"headline": h, "source": "EODHD-fallback", "fetched_at": ts}
                for h in _fallback_eodhd()]


def fetch_news_from_newsapi(max_results: int = MAX_PER_SOURCE) -> list[dict]:
    """
    NewsAPI — business category headlines.
    Debug proof: prints HTTP status, article count, and raw sample titles.
    """
    url    = "https://newsapi.org/v2/top-headlines"
    params = {"apiKey": NEWSAPI_API_KEY, "category": "business",
              "language": "en", "pageSize": max_results}
    ts     = utc_now()

    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data     = resp.json()
        articles = data.get("articles", [])

        dprint(f"\n  [DEBUG][NewsAPI] HTTP {resp.status_code} | fetched at {ts}")
        dprint(f"  [DEBUG][NewsAPI] API status     : {data.get('status','?')}"
               f" | Total results: {data.get('totalResults','?')}")
        if articles:
            dprint(f"  [DEBUG][NewsAPI] Sample title[0]: {articles[0].get('title','—')}")
        if len(articles) > 1:
            dprint(f"  [DEBUG][NewsAPI] Sample title[1]: {articles[1].get('title','—')}")

        items = [
            {
                "headline"  : a.get("title", "").strip(),
                "url"       : a.get("url", ""),
                "source"    : "NewsAPI",
                "fetched_at": ts,
            }
            for a in articles if a.get("title", "").strip()
        ]
        print(f"[NewsAPI]         Live headlines fetched : {len(items)}")
        return items

    except requests.exceptions.RequestException as e:
        print(f"[NewsAPI]         FAILED ({e}) — using fallback data.")
        return [{"headline": h, "source": "NewsAPI-fallback", "fetched_at": ts}
                for h in _fallback_newsapi()]


def fetch_news_from_yahoo_rss(max_results: int = MAX_PER_SOURCE) -> list[dict]:
    """
    Yahoo Finance RSS — XML feed.
    Debug proof: prints HTTP status, raw XML item count, and first item title.
    """
    url = "https://finance.yahoo.com/news/rssindex"
    ts  = utc_now()

    try:
        resp = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        resp.raise_for_status()

        root    = ET.fromstring(resp.content)
        channel = root.find("channel")
        items   = channel.findall("item") if channel is not None else []

        dprint(f"\n  [DEBUG][Yahoo] HTTP {resp.status_code} | fetched at {ts}")
        dprint(f"  [DEBUG][Yahoo] XML items found  : {len(items)}")
        if items:
            first_title = items[0].find("title")
            dprint(f"  [DEBUG][Yahoo] Sample title[0] : "
                   f"{first_title.text if first_title is not None else '—'}")

        headlines = []
        for item in items[:max_results]:
            t = item.find("title")
            lnk = item.find("link")
            if t is not None and t.text:
                headlines.append({
                    "headline"  : t.text.strip(),
                    "url"       : lnk.text.strip() if lnk is not None and lnk.text else "",
                    "source"    : "Yahoo",
                    "fetched_at": ts,
                })

        print(f"[Yahoo Finance]   Live headlines fetched : {len(headlines)}")
        return headlines

    except Exception as e:
        print(f"[Yahoo Finance]   FAILED ({e}) — using fallback data.")
        return [{"headline": h, "source": "Yahoo-fallback", "fetched_at": ts}
                for h in _fallback_yahoo()]


def fetch_news_from_alphavantage(max_results: int = MAX_PER_SOURCE) -> list[dict]:
    """
    Alpha Vantage NEWS_SENTIMENT — finance/economy topics.
    Debug proof: prints HTTP status, feed length, and first 2 raw titles.
    Free tier: 25 requests/day.
    """
    url    = "https://www.alphavantage.co/query"
    params = {"function": "NEWS_SENTIMENT", "apikey": ALPHAVANTAGE_API_KEY,
              "topics": "financial_markets,economy_macro,finance",
              "limit": max_results, "sort": "LATEST"}
    ts     = utc_now()

    try:
        resp = requests.get(url, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
        feed = data.get("feed", [])

        dprint(f"\n  [DEBUG][AlphaVantage] HTTP {resp.status_code} | fetched at {ts}")
        dprint(f"  [DEBUG][AlphaVantage] Feed items     : {len(feed)}")
        # Alpha Vantage returns an 'Information' key when rate-limited
        if "Information" in data:
            dprint(f"  [DEBUG][AlphaVantage] ⚠ API message : {data['Information']}")
        if feed:
            dprint(f"  [DEBUG][AlphaVantage] Sample title[0]: {feed[0].get('title','—')}")
        if len(feed) > 1:
            dprint(f"  [DEBUG][AlphaVantage] Sample title[1]: {feed[1].get('title','—')}")

        items = [
            {
                "headline"  : f.get("title", "").strip(),
                "url"       : f.get("url", ""),
                "source"    : "AlphaVantage",
                "fetched_at": ts,
            }
            for f in feed if f.get("title", "").strip()
        ]
        print(f"[Alpha Vantage]   Live headlines fetched : {len(items)}")
        return items

    except requests.exceptions.RequestException as e:
        print(f"[Alpha Vantage]   FAILED ({e}) — using fallback data.")
        return [{"headline": h, "source": "AlphaVantage-fallback", "fetched_at": ts}
                for h in _fallback_alphavantage()]


# ===========================================================================
# STEP 2 — FILTER & MERGE (now operates on dicts)
# ===========================================================================

def filter_finance_items(items: list[dict]) -> list[dict]:
    """Filter items whose headline matches finance keywords."""
    return [i for i in items if is_finance_relevant(i["headline"])]


def merge_and_deduplicate_items(
    *source_lists: list[dict],
    max_total: int = MAX_HEADLINES,
) -> list[dict]:
    """
    Merge all source lists, deduplicate by lowercase headline,
    and cap at max_total. Preserves source + timestamp metadata.
    """
    seen     = set()
    combined = []

    for source in source_lists:
        for item in source:
            key = item["headline"].strip().lower()
            if key and key not in seen:
                seen.add(key)
                combined.append(item)
            if len(combined) >= max_total:
                break
        if len(combined) >= max_total:
            break

    print(f"\n[Merge]           Unique finance headlines : {len(combined)}")
    return combined


# ===========================================================================
# STEP 3 — LOAD FINBERT + SELF-TEST
# ===========================================================================

def load_finbert_model():
    """
    Load ProsusAI/finbert from Hugging Face.
    In DEBUG_MODE, runs a 3-sentence self-test first so you can confirm
    the model is producing sensible outputs before processing real news.

    Self-test expected results:
        "Profits surged to record high"  → POSITIVE
        "Market closed unchanged today"  → NEUTRAL
        "Company files for bankruptcy"   → NEGATIVE
    """
    print(f"\n[FinBERT]  Loading '{FINBERT_MODEL}'...")
    t0 = time.time()

    tokenizer = AutoTokenizer.from_pretrained(FINBERT_MODEL)
    model     = AutoModelForSequenceClassification.from_pretrained(FINBERT_MODEL)
    fb        = pipeline(task="text-classification", model=model,
                         tokenizer=tokenizer, truncation=True, max_length=512)

    elapsed = round(time.time() - t0, 1)
    print(f"[FinBERT]  Model loaded in {elapsed}s.\n")

    # ── DEBUG: Self-test with 3 sentences of known expected sentiment ──────
    if DEBUG_MODE:
        print("  [DEBUG][FinBERT] Running self-test on 3 known sentences...")
        self_test_cases = [
            ("Company profits surged to a record high this quarter.",   "positive"),
            ("The market closed largely unchanged on Monday.",           "neutral"),
            ("The firm announced it is filing for bankruptcy.",          "negative"),
        ]
        all_passed = True
        for sentence, expected in self_test_cases:
            result = fb(sentence)[0]
            actual = result["label"].lower()
            score  = round(result["score"], 3)
            status = "✅ PASS" if actual == expected else "❌ FAIL"
            if actual != expected:
                all_passed = False
            print(f"    {status}  [{actual.upper():<8} {score:.3f}]  \"{sentence}\"")
        verdict = "✅ FinBERT is working correctly." if all_passed \
                  else "⚠️  Some labels differ — model may produce unexpected results."
        print(f"\n  [DEBUG][FinBERT] Self-test result: {verdict}\n")

    return fb


# ===========================================================================
# STEP 4 — PER-HEADLINE SENTIMENT
# ===========================================================================

def get_sentiment(item: dict, finbert_pipeline) -> dict:
    """
    Classify one headline dict and return an enriched result dict.
    Preserves source, url, and fetched_at so the API can return them.
    """
    output = finbert_pipeline(item["headline"])[0]
    return {
        "headline"  : item["headline"],
        "label"     : output["label"].lower(),
        "score"     : round(output["score"], 4),
        "source"    : item.get("source", "unknown"),
        "url"       : item.get("url", ""),
        "fetched_at": item.get("fetched_at", "—"),
    }


# ===========================================================================
# STEP 5 — AGGREGATE SENTIMENT
# ===========================================================================

def aggregate_sentiment(results: list[dict]) -> str:
    counts = {"positive": 0, "neutral": 0, "negative": 0}
    for r in results:
        counts[r.get("label", "neutral")] += 1

    total = sum(counts.values()) or 1

    print("\n[Sentiment Aggregation]")
    print(f"  {'Label':<12} {'Count':>5}   {'Share':>6}   Bar")
    print("  " + "-" * 46)
    for label, count in counts.items():
        pct = round(100 * count / total, 1)
        bar = "█" * max(1, int(pct / 5))
        print(f"  {label.capitalize():<12} {count:>5}   {pct:>5.1f}%   {bar}")

    return max(counts, key=counts.get)


# ===========================================================================
# STEP 6 — CATEGORY DETECTION
# ===========================================================================

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "Mutual Funds"      : ["mutual fund", "mutual funds", "sip", "nav", "amc",
                           "elss", "index fund", "debt fund", "liquid fund",
                           "hybrid fund", "folio"],
    "Stocks & Indices"  : ["stock", "stocks", "equity", "share", "ipo", "sensex",
                           "nifty", "bse", "nse", "nasdaq", "dow jones", "s&p",
                           "ftse", "rally", "earnings", "dividend", "buyback",
                           "smallcap", "midcap", "bull", "bear", "crash"],
    "Banking"           : ["bank", "banking", "rbi", "fed", "federal reserve",
                           "repo rate", "nbfc", "credit", "loan", "deposit",
                           "npa", "interest rate", "fixed deposit", "fd"],
    "Economy & Inflation": ["economy", "economic", "inflation", "deflation",
                            "gdp", "cpi", "wpi", "fiscal", "monetary",
                            "budget", "trade deficit", "recession"],
    "Commodities"       : ["gold", "silver", "crude", "oil", "commodity",
                           "commodities", "metal", "copper", "wheat"],
    "Technology"        : ["tech", "it sector", "software", "saas",
                           "semiconductor", "startup", "fintech", "digital"],
}

_CATEGORY_PATTERNS: dict[str, re.Pattern] = {
    cat: re.compile(
        r"\b(" + "|".join(re.escape(kw) for kw in kws) + r")\b",
        flags=re.IGNORECASE,
    )
    for cat, kws in CATEGORY_KEYWORDS.items()
}


def detect_category(headline: str) -> str | None:
    for cat, pattern in _CATEGORY_PATTERNS.items():
        if pattern.search(headline):
            return cat
    return None


def find_trending_category(results: list[dict]) -> str:
    counts: dict[str, int] = {}
    for r in results:
        cat = detect_category(r["headline"])
        if cat:
            counts[cat] = counts.get(cat, 0) + 1
    if not counts:
        return "General Market"
    dprint(f"\n  [DEBUG][Category] Full count breakdown: {counts}")
    return max(counts, key=counts.get)


# ===========================================================================
# STEP 7 — GENERATE RECOMMENDATION
# ===========================================================================

_TEMPLATES = {
    "positive": (
        "Based on positive market sentiment and trending {category} news, "
        "you may consider investing a portion of your savings in {category}. "
        "Market conditions look favourable — even a small SIP or lump-sum "
        "allocation could work in your favour right now."
    ),
    "neutral": (
        "Market sentiment is currently mixed, with notable activity in {category}. "
        "A cautious, diversified approach — such as a balanced mutual fund or "
        "multi-asset fund — may be the most prudent use of your savings."
    ),
    "negative": (
        "Markets are showing negative sentiment, particularly around {category}. "
        "Consider parking your savings in a stable instrument — such as a liquid "
        "fund, short-term FD, or RBI Floating Rate Bond — until conditions improve."
    ),
}


def generate_copilot_response(savings: float, sentiment: str,
                               category: str, currency: str = "₹") -> str:
    body = _TEMPLATES.get(sentiment, _TEMPLATES["neutral"]).format(category=category)
    return f"You saved {currency}{savings:,.0f} this month. {body}"


# ===========================================================================
# DEBUG: PIPELINE SUMMARY REPORT
# Prints after all steps — gives a birds-eye verification at the end.
# ===========================================================================

def print_debug_summary(results: list[dict], overall_sentiment: str,
                        trending: str, pipeline_start: float) -> None:
    if not DEBUG_MODE:
        return

    elapsed    = round(time.time() - pipeline_start, 1)
    src_counts = {}
    live_count = 0
    for r in results:
        src = r.get("source", "unknown")
        src_counts[src] = src_counts.get(src, 0) + 1
        if "fallback" not in src.lower():
            live_count += 1

    print("\n" + "─" * 68)
    print("  [DEBUG] PIPELINE VERIFICATION SUMMARY")
    print("─" * 68)
    print(f"  Pipeline completed in     : {elapsed}s")
    print(f"  Total headlines processed : {len(results)}")
    print(f"  Live headlines (not fallback): {live_count} / {len(results)}")
    print(f"\n  Headlines by source:")
    for src, cnt in sorted(src_counts.items()):
        tag = "✅ LIVE" if "fallback" not in src.lower() else "⚠️  FALLBACK"
        print(f"    {tag}  {src:<25} : {cnt}")
    print(f"\n  Final sentiment  : {overall_sentiment.upper()}")
    print(f"  Trending category: {trending}")
    ts_vals = [r.get("fetched_at", "") for r in results if "fallback" not in r.get("source","")]
    if ts_vals:
        print(f"\n  Data freshness   : fetched at {ts_vals[0]} (UTC)")
        print(f"  ✅ Timestamps confirm this is LIVE data, not cached/static.")
    else:
        print(f"\n  ⚠️  All data came from fallback — no live API data was used.")
        print(f"     Check your API keys and network connection.")
    print("─" * 68 + "\n")


# ===========================================================================
# MAIN PIPELINE
# ===========================================================================

def run_finverse_pipeline(user_savings: float = 15_000.0) -> None:
    pipeline_start = time.time()

    print("\n" + "=" * 68)
    print("  FINVERSE — Financial Sentiment & Investment Copilot  (v3)")
    if DEBUG_MODE:
        print("  [DEBUG MODE ON — full verification output enabled]")
    print("=" * 68)

    # ── 1. Fetch ──────────────────────────────────────────────────────────────
    print(f"\n[Step 1] Fetching live news  [{utc_now()}]")
    raw_eodhd   = fetch_news_from_eodhd()
    raw_newsapi = fetch_news_from_newsapi()
    raw_yahoo   = fetch_news_from_yahoo_rss()
    raw_alpha   = fetch_news_from_alphavantage()

    # ── 2. Filter ─────────────────────────────────────────────────────────────
    print("\n[Step 2] Filtering for finance relevance...")
    fin_eodhd   = filter_finance_items(raw_eodhd)
    fin_newsapi = filter_finance_items(raw_newsapi)
    fin_yahoo   = filter_finance_items(raw_yahoo)
    fin_alpha   = filter_finance_items(raw_alpha)

    print(f"  EODHD          : {len(raw_eodhd):>2} raw → {len(fin_eodhd):>2} kept")
    print(f"  NewsAPI        : {len(raw_newsapi):>2} raw → {len(fin_newsapi):>2} kept")
    print(f"  Yahoo Finance  : {len(raw_yahoo):>2} raw → {len(fin_yahoo):>2} kept")
    print(f"  Alpha Vantage  : {len(raw_alpha):>2} raw → {len(fin_alpha):>2} kept")

    # ── 3. Merge & deduplicate ────────────────────────────────────────────────
    print("\n[Step 3] Merging and deduplicating...")
    items = merge_and_deduplicate_items(fin_eodhd, fin_newsapi, fin_yahoo, fin_alpha)

    if not items:
        print("\n[ERROR] No finance headlines found. Check API keys / network.")
        return

    # ── 4. Load FinBERT (includes self-test in debug mode) ────────────────────
    print("\n[Step 4] Loading FinBERT model...")
    finbert = load_finbert_model()

    # ── 5. Classify every headline ────────────────────────────────────────────
    print("[Step 5] Classifying headlines...\n")
    results   = []
    emoji_map = {"positive": "🟢", "neutral": "🟡", "negative": "🔴"}

    for i, item in enumerate(items, start=1):
        result = get_sentiment(item, finbert)
        results.append(result)

        emoji     = emoji_map.get(result["label"], "⚪")
        label_str = f"[{result['label'].upper():<8} {result['score']:.4f}]"
        short     = result["headline"][:72] + "…" if len(result["headline"]) > 72 else result["headline"]

        # In debug mode show source + timestamp on each line
        src_tag = f"  ← {result['source']} @ {result['fetched_at']}" if DEBUG_MODE else ""
        print(f"  {i:>2}. {emoji} {label_str}  {short}")
        if DEBUG_MODE:
            print(f"       📡 Source: {result['source']}  |  🕐 {result['fetched_at']}")

    # ── 6. Aggregate ─────────────────────────────────────────────────────────
    print("\n[Step 6] Aggregating sentiment...")
    overall_sentiment = aggregate_sentiment(results)
    print(f"\n  ➤ Overall Market Sentiment : {overall_sentiment.upper()}")

    # ── 7. Category ───────────────────────────────────────────────────────────
    print("\n[Step 7] Detecting trending category...")
    trending = find_trending_category(results)
    print(f"  ➤ Trending Category        : {trending}")

    # ── 8. Recommendation ────────────────────────────────────────────────────
    recommendation = generate_copilot_response(
        savings=user_savings, sentiment=overall_sentiment, category=trending
    )

    print("\n" + "=" * 68)
    print("  💡 FINVERSE COPILOT RECOMMENDATION")
    print("=" * 68)
    print(f"\n  {recommendation}\n")
    print("=" * 68)

    # ── DEBUG: Final summary report ───────────────────────────────────────────
    print_debug_summary(results, overall_sentiment, trending, pipeline_start)


# ===========================================================================
# ENTRY POINT
# ===========================================================================

if __name__ == "__main__":
    USER_SAVINGS = 15_000          # Monthly savings in ₹
    run_finverse_pipeline(user_savings=USER_SAVINGS)